// Copyright (c) rAthena Dev Teams - Licensed under GNU GPL
// For more information, see LICENCE in the main folder
//
// Per-map difficulty lookup. Loaded from db/ai/map_difficulty.yml at startup;
// regenerated by tools/ai/compute_map_difficulty.py from mob_db + spawn files.
//
// Used by the spawner to pick a profile tier matching the map's mob level
// instead of using a fixed tier-per-category mapping (which sent a lvl-35
// High Mage into a lvl-80 field).

#ifndef AI_MAP_DIFFICULTY_HPP
#define AI_MAP_DIFFICULTY_HPP

#include <common/cbasetypes.hpp>

namespace rathena::server_ai {

bool map_difficulty_load(const char* yaml_path);

/// Average mob level on `map`, or 0 if unknown (no spawn data).
uint16 map_difficulty_avg_level(const char* map_name);

/// Tier index for a map: 0 = <25, 1 = 25-49, 2 = >=50. Unknown maps return 1
/// (mid) so they don't silently get the lowest profile.
uint8 map_difficulty_tier(const char* map_name);

}

#endif /* AI_MAP_DIFFICULTY_HPP */
