"""Compute average mob level per map and emit db/ai/map_difficulty.yml.

The ai-server uses this file to pick a profile tier matching map difficulty,
so a Mage on prt_fild01 spawns lvl ~10 and a Wizard on gef_fild06 spawns lvl
~75 — instead of every shell spawning at job's hardcoded T0 level.

Usage:
    python tools/ai/compute_map_difficulty.py [--mode re|pre-re]

Inputs:
    db/<mode>/mob_db.yml          — Id -> Level
    npc/<mode>/mobs/{fields,dungeons}/*.txt   — map -> [(mob_id, weight)]

Output:
    db/ai/map_difficulty.yml
"""

from __future__ import annotations

import argparse
import os
import re
import sys
from pathlib import Path

# ryml/PyYAML is not guaranteed in the rA build env, parse mob_db.yml minimally.
MOB_ID_RE = re.compile(r"^\s*-\s*Id:\s*(\d+)")
MOB_LEVEL_RE = re.compile(r"^\s*Level:\s*(\d+)")

# Spawn-line format we care about:
# <map>,<x>,<y>[,<xs>,<ys>]\t(monster|boss_monster)\t<Name>\t<id>,<count>,...
# Tabs may also be spaces. We only need map and id.
SPAWN_RE = re.compile(
    r"^([a-z0-9_]+),\d+,\d+(?:,\d+,\d+)?\s+(?:monster|boss_monster)\s+\S.*?\s+(\d+),(\d+),"
)


def parse_mob_levels(mob_db_path: Path) -> dict[int, int]:
    """Walk mob_db.yml line by line: pair each Id with the next Level we see."""
    levels: dict[int, int] = {}
    cur_id: int | None = None
    with mob_db_path.open(encoding="utf-8") as f:
        for line in f:
            m = MOB_ID_RE.match(line)
            if m:
                cur_id = int(m.group(1))
                continue
            if cur_id is not None:
                lm = MOB_LEVEL_RE.match(line)
                if lm:
                    levels[cur_id] = int(lm.group(1))
                    cur_id = None  # one Level per Id
    return levels


def parse_spawns(spawn_dirs: list[Path]) -> dict[str, list[tuple[int, int]]]:
    """map -> list of (mob_id, count). count is the spawn weight."""
    out: dict[str, list[tuple[int, int]]] = {}
    for d in spawn_dirs:
        if not d.exists():
            continue
        for path in d.rglob("*.txt"):
            try:
                with path.open(encoding="utf-8", errors="ignore") as f:
                    for line in f:
                        m = SPAWN_RE.match(line)
                        if not m:
                            continue
                        map_name, mob_id_s, count_s = m.group(1), m.group(2), m.group(3)
                        mob_id = int(mob_id_s)
                        count = int(count_s)
                        if count <= 0:
                            continue
                        out.setdefault(map_name, []).append((mob_id, count))
            except OSError:
                continue
    return out


def avg_level(spawns: list[tuple[int, int]], levels: dict[int, int]) -> int:
    """Weighted average mob level, ignoring mobs we couldn't resolve."""
    total_weight = 0
    weighted_sum = 0
    for mob_id, count in spawns:
        lvl = levels.get(mob_id)
        if lvl is None or lvl <= 0:
            continue
        # Skip plants and trivial mobs (lvl 1) — they distort low-end averages.
        if lvl < 2:
            continue
        total_weight += count
        weighted_sum += lvl * count
    if total_weight == 0:
        return 0
    return weighted_sum // total_weight


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--mode", choices=("re", "pre-re"), default="re")
    parser.add_argument(
        "--root",
        type=Path,
        default=Path(__file__).resolve().parents[2],
        help="rathena root (default: repo root)",
    )
    args = parser.parse_args()

    root: Path = args.root
    mob_db = root / "db" / args.mode / "mob_db.yml"
    if not mob_db.exists():
        print(f"ERROR: mob_db not found at {mob_db}", file=sys.stderr)
        return 1

    spawn_dirs = [
        root / "npc" / args.mode / "mobs" / "fields",
        root / "npc" / args.mode / "mobs" / "dungeons",
    ]

    print(f"reading {mob_db}")
    levels = parse_mob_levels(mob_db)
    print(f"  {len(levels)} mobs with levels")

    print(f"reading spawns from {[str(d) for d in spawn_dirs]}")
    spawns = parse_spawns(spawn_dirs)
    print(f"  {len(spawns)} maps with spawns")

    rows: list[tuple[str, int]] = []
    for m in sorted(spawns):
        avg = avg_level(spawns[m], levels)
        if avg == 0:
            continue
        rows.append((m, avg))

    out_path = root / "db" / "ai" / "map_difficulty.yml"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("w", encoding="utf-8") as f:
        f.write("# Auto-generated by tools/ai/compute_map_difficulty.py.\n")
        f.write("# Average mob level per map. Used by ai-server to pick the\n")
        f.write("# profile tier matching map difficulty.\n")
        f.write("Header:\n  Type: AI_MAP_DIFFICULTY\n  Version: 1\n")
        f.write("Body:\n")
        for m, avg in rows:
            f.write(f"  - Map: {m}\n    AvgLevel: {avg}\n")

    print(f"wrote {out_path} ({len(rows)} maps)")

    # Quick distribution preview
    bands = {"T0(<25)": 0, "T1(25-50)": 0, "T2(>=50)": 0}
    for _, avg in rows:
        if avg < 25:
            bands["T0(<25)"] += 1
        elif avg < 50:
            bands["T1(25-50)"] += 1
        else:
            bands["T2(>=50)"] += 1
    for k, v in bands.items():
        print(f"  {k}: {v} maps")
    return 0


if __name__ == "__main__":
    sys.exit(main())
